### ISSUE TITLE
05. ansible facts - solution: wrong hostgroup in the command line to verify

### ISSUE THREAD

**Issue by MrP1xel** [mateuszstompor/rhce-ex294-exam#4]
ansible database -m setup | grep ansible_local -A 3

Should be 

ansible proxy -m setup | grep ansible_local -A 3

**Comment by mateuszstompor** [comment]
@MrP1xel Thank you for finding it and letting me know! Would you like to open a PR for the fix?

**Comment by mateuszstompor** [comment]
Resolved in https://github.com/mateuszstompor/rhce-ex294-exam/pull/5
